exclude: ^.vscode
default_language_version:
  python: python3.13
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-toml
  - id: check-vcs-permalinks
  - id: check-yaml
    args: [--allow-multiple-documents]
    exclude: helm-charts/
  - id: detect-private-key
  - id: detect-aws-credentials
    args: [--allow-missing-credentials]
  - id: pretty-format-json
    args: [--no-sort-keys, --autofix]
  - id: fix-encoding-pragma
    args: [--remove]
  - id: fix-byte-order-marker
  - id: mixed-line-ending
  - id: no-commit-to-branch
    args: [--branch, master]
  - id: requirements-txt-fixer
  - id: sort-simple-yaml
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]

- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
  - id: black
    language_version: python3.13

- repo: https://github.com/pycqa/flake8
  rev: 7.3.0
  hooks:
  - id: flake8

- repo: https://github.com/pycqa/bandit
  rev: 1.8.6
  hooks:
  - id: bandit
    args: [-x, "**/tests/*,**/e2e/*", -r]

- repo: https://github.com/pycqa/isort
  rev: 6.0.1
  hooks:
  - id: isort
    args: [--filter-files]
    files: \.py$
